"""Constants for the Dooya RS485 integration."""
from homeassistant.components.cover import CoverEntityFeature

DOMAIN = "dooya_rs485"

# RS485 Protocol Constants
START_CODE = 0x55

# Command Types
CURTAIN_READ = 0x01
CURTAIN_WRITE = 0x02
CURTAIN_COMMAND = 0x03

# Commands
CURTAIN_COMMAND_OPEN = 0x01
CURTAIN_COMMAND_CLOSE = 0x02
CURTAIN_COMMAND_STOP = 0x03
CURTAIN_COMMAND_PERCENT = 0x04
CURTAIN_COMMAND_DELETE = 0x07
CURTAIN_COMMAND_RESET = 0x08

# Read/Write Registers
CURTAIN_READ_WRITE_ADDR_LOW = 0x00
CURTAIN_READ_WRITE_ADDR_HIGH = 0x01
CURTAIN_READ_WRITE_ADDR = 0x00
CURTAIN_READ_WRITE_PERCENT = 0x02
CURTAIN_READ_WRITE_DIRECTION = 0x03
CURTAIN_READ_WRITE_HANDLE = 0x04
CURTAIN_READ_WRITE_MOTOR_STATUS = 0x05
CURTAIN_READ_WRITE_SWITCH_PASSIVE = 0x27
CURTAIN_READ_WRITE_SWITCH_ACTIVE = 0x28
CURTAIN_READ_WRITE_VERSION = 0xFE

# Status Codes
MOTOR_STATUS_STOPPED = 0x00
MOTOR_STATUS_RUNNING = 0x01
MOTOR_STATUS_ERROR = 0x02

SWITCH_STATUS_NORMAL = 0x00
SWITCH_STATUS_TRIGGERED = 0x01

HANDLE_STATUS_NORMAL = 0x00
HANDLE_STATUS_OPERATED = 0x01

# Cover Features
SUPPORTED_FEATURES = (
    CoverEntityFeature.OPEN |
    CoverEntityFeature.CLOSE |
    CoverEntityFeature.STOP
)
