DOMAIN = "dooya_rs485"

START_CODE = 0x55

CURTAIN_READ = 0x01
CURTAIN_WRITE = 0x02
CURTAIN_COMMAND = 0x03

# COMMANDS
CURTAIN_COMMAND_OPEN = 0x01
CURTAIN_COMMAND_CLOSE = 0x02
CURTAIN_COMMAND_STOP = 0x03
CURTAIN_COMMAND_PERCENT = 0x04
CURTAIN_COMMAND_DELETE = 0x07
CURTAIN_COMMAND_RESET = 0x08

# READ/WRITE
CURTAIN_READ_WRITE_ADDR_LOW = 0x00
CURTAIN_READ_WRITE_ADDR_HIGH = 0x01
CURTAIN_READ_WRITE_ADDR	=	0x00
CURTAIN_READ_WRITE_PERCENT = 0x02
CURTAIN_READ_WRITE_DIRECTION = 0x03
CURTAIN_READ_WRITE_HANDLE	= 0x04
CURTAIN_READ_WRITE_MOTOR_STATUS = 0x05
CURTAIN_READ_WRITE_SWITCH_PASSIVE = 0x27
CURTAIN_READ_WRITE_SWITCH_ACTIVE = 0x28
CURTAIN_READ_WRITE_VERSION = 0xfe
